name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        eslint-version: [6.x]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use ESLint ${{ matrix.eslint-version }}
      run: |
        npm install --no-save eslint@${{ matrix.eslint-version }}
        ./node_modules/.bin/eslint *.js
